name: Build MagicalSpears Plugin

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Repository Checkout
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Set up JDK 17 (for Minecraft 1.21.1)
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    # 4️⃣ Build with Maven
    - name: Build plugin using Maven
      run: mvn -B clean package

    # 5️⃣ Upload compiled .jar artifact
    - name: Upload Plugin Jar
      uses: actions/upload-artifact@v4
      with:
        name: MagicalSpears-jar
        path: target/*.jar
        
